In [1]:
import numpy as np

In [11]:
x = np.arange(4)
xx = x.reshape(4,1)
y = np.ones(5)
z = np.ones((3,4))

In [48]:
a = np.array([0.0, 10.0, 20.0, 30.0])
b = np.array([1.0, 2.0, 3.0])

In [50]:
b.shape

(3,)

In [51]:
a[:, np.newaxis] + b

array([[ 1.,  2.,  3.],
       [11., 12., 13.],
       [21., 22., 23.],
       [31., 32., 33.]])

In [85]:
X = np.arange(12)
X = X.reshape(6, 2)
X

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [86]:
Y = np.arange(6)
Y = Y.reshape(3, 2)
Y

array([[0, 1],
       [2, 3],
       [4, 5]])

In [87]:
X**2

array([[  0,   1],
       [  4,   9],
       [ 16,  25],
       [ 36,  49],
       [ 64,  81],
       [100, 121]], dtype=int32)

In [92]:
np.sum(X**2, axis= 1)

array([  1,  13,  41,  85, 145, 221], dtype=int32)

In [89]:
Y**2

array([[ 0,  1],
       [ 4,  9],
       [16, 25]], dtype=int32)

In [94]:
np.sum(Y**2, axis=1)

array([ 1, 13, 41], dtype=int32)

In [91]:
np.dot(Y,X.T)

array([[ 1,  3,  5,  7,  9, 11],
       [ 3, 13, 23, 33, 43, 53],
       [ 5, 23, 41, 59, 77, 95]])

In [101]:
np.sqrt(np.sum(X**2, axis= 1) -2 *  np.dot(Y,X.T) + np.sum(Y**2, axis=1)[:,np.newaxis])

array([[ 0.        ,  2.82842712,  5.65685425,  8.48528137, 11.3137085 ,
        14.14213562],
       [ 2.82842712,  0.        ,  2.82842712,  5.65685425,  8.48528137,
        11.3137085 ],
       [ 5.65685425,  2.82842712,  0.        ,  2.82842712,  5.65685425,
         8.48528137]])

In [100]:
compute_distances_two_loops(Y,X)

array([[ 0.        ,  2.82842712,  5.65685425],
       [ 2.82842712,  0.        ,  2.82842712],
       [ 5.65685425,  2.82842712,  0.        ],
       [ 8.48528137,  5.65685425,  2.82842712],
       [11.3137085 ,  8.48528137,  5.65685425],
       [14.14213562, 11.3137085 ,  8.48528137]])

In [ ]:
import numpy as np
folds = np.array_split(kdata, k) # each fold is 19 rows x 9 columns
np.random.shuffle(kdata) # Shuffle all rows
folds = np.array_split(kdata, k)

for i in range (k):
    xtest = folds[i][:,:8] # Set ith fold to be test
    ytest = folds[i][:,8]
    new_folds = np.row_stack(np.delete(folds,i,0))
    xtrain = new_folds[:, :8]
    ytrain = new_folds[:,8]

    # some print functions to help you debug
    print(f'Fold {i}')
    print(f'xtest shape  : {xtest.shape}')
    print(f'ytest shape  : {ytest.shape}')
    print(f'xtrain shape : {xtrain.shape}')
    print(f'ytrain shape : {ytrain.shape}\n')

In [3]:
import numpy as np

X = np.array([[1, 1, 1],
              [0, 1, 1],
              [0, 1, 1]])
Y = np.array([[0],
             [1],
             [1]])
W = np.array([[2, 1, 0],
              [1, 1, 2]])
W

array([[2, 1, 1, 0],
       [1, 1, 0, 2]])

In [7]:
W.dot(X.T)

array([[4, 2, 1],
       [4, 3, 3]])

In [7]:
a = {}
key = [('a', 'b')]
value = [('c','d')]
a = dict(zip(key,value))
a[(1, 2)] = [(2,22)]
a

{('a', 'b'): ('c', 'd'), (1, 2): [(2, 22)]}

In [34]:
learning_rates = [1e-7, 5e-5]
regularization_strengths = [2.5e4, 5e4,]
results ={}

results[3, 2] = (2, 1)
results[4, 6] = (1, 3)

best_val = max(results.values()) []  # maximum value
best_svm = [k for k, v in results.items() if v == best_val ] # getting all keys containing the `maximum`
print(best_val)
print(best_svm)

SyntaxError: can't assign to function call (<ipython-input-34-d529ea05edb6>, line 9)

In [2]:
import numpy as np
def stable_softmax(X):
    exps = np.exp(X - np.max(X))
    return exps / np.sum(exps)

In [9]:
X = [0.4, 0.5, 0.1]
sum(stable_softmax(X))
stable_softmax(X)

array([0.35137169, 0.38832577, 0.26030255])

In [54]:
import numpy as np

X = np.array([[1, 1, 1],
              [0, 1, 1],
              [0, 1, 1]])
Y = np.array([0, 1, 1])
W = np.array([[2, 1, 0],
              [1, 1, 2]])
W = W.T

In [11]:
W

array([[2, 1],
       [1, 1],
       [0, 2]])

In [55]:
loss = 0.0
dW = np.zeros_like(W)

N = X.shape[0]
C = W.shape[1]

f = X.dot(W)


In [56]:
f

array([[3, 4],
       [1, 3],
       [1, 3]])

In [70]:
f -= np.matrix(np.max(f, axis=1)).T
print(f)
term1 = -f[np.arange(N), Y]
term1 
sum_j = np.sum(np.exp(f), axis=1)
print(sum_j)
term2 = np.log(sum_j)
loss = term1 + term2
loss = np.sum(loss)
loss /= N 

loss += 0.5 * 0.0001 * np.sum(W * W)
# loss

[[-1  0]
 [-2  0]
 [-2  0]]
[1.36787944 1.13533528 1.13533528]


In [67]:
coef = np.exp(f) / np.matrix(sum_j).T
coef[np.arange(N),Y] -= 1
dW = X.T.dot(coef)
dW /= N
dW += 0.001*W
dW

matrix([[-0.24168619,  0.24468619],
        [-0.16321758,  0.16521758],
        [-0.16421758,  0.16621758]])