In [1]:
import numpy as np

In [11]:
x = np.arange(4)
xx = x.reshape(4,1)
y = np.ones(5)
z = np.ones((3,4))

In [48]:
a = np.array([0.0, 10.0, 20.0, 30.0])
b = np.array([1.0, 2.0, 3.0])

In [50]:
b.shape

(3,)

In [51]:
a[:, np.newaxis] + b

array([[ 1.,  2.,  3.],
       [11., 12., 13.],
       [21., 22., 23.],
       [31., 32., 33.]])

In [85]:
X = np.arange(12)
X = X.reshape(6, 2)
X

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [86]:
Y = np.arange(6)
Y = Y.reshape(3, 2)
Y

array([[0, 1],
       [2, 3],
       [4, 5]])

In [87]:
X**2

array([[  0,   1],
       [  4,   9],
       [ 16,  25],
       [ 36,  49],
       [ 64,  81],
       [100, 121]], dtype=int32)

In [92]:
np.sum(X**2, axis= 1)

array([  1,  13,  41,  85, 145, 221], dtype=int32)

In [89]:
Y**2

array([[ 0,  1],
       [ 4,  9],
       [16, 25]], dtype=int32)

In [94]:
np.sum(Y**2, axis=1)

array([ 1, 13, 41], dtype=int32)

In [91]:
np.dot(Y,X.T)

array([[ 1,  3,  5,  7,  9, 11],
       [ 3, 13, 23, 33, 43, 53],
       [ 5, 23, 41, 59, 77, 95]])

In [101]:
np.sqrt(np.sum(X**2, axis= 1) -2 *  np.dot(Y,X.T) + np.sum(Y**2, axis=1)[:,np.newaxis])

array([[ 0.        ,  2.82842712,  5.65685425,  8.48528137, 11.3137085 ,
        14.14213562],
       [ 2.82842712,  0.        ,  2.82842712,  5.65685425,  8.48528137,
        11.3137085 ],
       [ 5.65685425,  2.82842712,  0.        ,  2.82842712,  5.65685425,
         8.48528137]])

In [100]:
compute_distances_two_loops(Y,X)

array([[ 0.        ,  2.82842712,  5.65685425],
       [ 2.82842712,  0.        ,  2.82842712],
       [ 5.65685425,  2.82842712,  0.        ],
       [ 8.48528137,  5.65685425,  2.82842712],
       [11.3137085 ,  8.48528137,  5.65685425],
       [14.14213562, 11.3137085 ,  8.48528137]])

In [ ]:
import numpy as np
folds = np.array_split(kdata, k) # each fold is 19 rows x 9 columns
np.random.shuffle(kdata) # Shuffle all rows
folds = np.array_split(kdata, k)

for i in range (k):
    xtest = folds[i][:,:8] # Set ith fold to be test
    ytest = folds[i][:,8]
    new_folds = np.row_stack(np.delete(folds,i,0))
    xtrain = new_folds[:, :8]
    ytrain = new_folds[:,8]

    # some print functions to help you debug
    print(f'Fold {i}')
    print(f'xtest shape  : {xtest.shape}')
    print(f'ytest shape  : {ytest.shape}')
    print(f'xtrain shape : {xtrain.shape}')
    print(f'ytrain shape : {ytrain.shape}\n')